"""Initial schema

Revision ID: 030f011a9a95
Revises: None
Create Date: 2026-07-30 09:45:48.365848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '030f011a9a95'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('consent_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('session2_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_session_id'), 'participants', ['session_id'], unique=True)
    op.create_table('responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.String(length=50), nullable=False),
    sa.Column('question_type', sa.Enum('REI', 'CRT', 'FREE_RECALL', 'FACTUAL', 'INTERPRETIVE', 'EMOTIONAL', 'AUDIO_EVENT', 'VIDEO_EVENT', name='question_type_enum'), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_value', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responses_participant_id'), 'responses', ['participant_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('rei_experiential', sa.Float(), nullable=True),
    sa.Column('rei_rational', sa.Float(), nullable=True),
    sa.Column('crt_score', sa.Integer(), nullable=True),
    sa.Column('factual_divergence', sa.Float(), nullable=True),
    sa.Column('interpretive_divergence', sa.Float(), nullable=True),
    sa.Column('emotional_divergence', sa.Float(), nullable=True),
    sa.Column('overall_divergence_immediate', sa.Float(), nullable=True),
    sa.Column('overall_divergence_delayed', sa.Float(), nullable=True),
    sa.Column('ai_interpretation_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_participant_id'), 'scores', ['participant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_participant_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_responses_participant_id'), table_name='responses')
    op.drop_table('responses')
    op.drop_index(op.f('ix_participants_session_id'), table_name='participants')
    op.drop_table('participants')
    # ### end Alembic commands ###
