"""add_session1_progress_columns

Revision ID: 77f0ecd3d07e
Revises: a1b2c3d4e5f6
Create Date: 2026-08-06 10:12:55.424453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77f0ecd3d07e'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('session1_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('participants', sa.Column('session1_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'session1_completed_at')
    op.drop_column('participants', 'session1_completed')
    # ### end Alembic commands ###
